import type { Metadata } from "next";
import {
  century,
  creatorsWavy,
  trajanProBold,
  trajanProRegular,
  burguesScript,
  elMessiri,
  cylburn,
  notoSans,
  ibmPlexSans
} from "@/lib/fonts";
import "./globals.css";
import AOSInit from "@/components/AOSINIT";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSans.variable}  ${ibmPlexSans.variable} ${century.variable} ${creatorsWavy.variable} ${trajanProBold.variable} ${trajanProRegular.variable} ${burguesScript.variable} ${cylburn.variable} ${elMessiri.variable}`}
    >
      <body>
        <AOSInit />

        {children}
      </body>
    </html>
  );
}
